# Generated by Django 2.2 on 2020-03-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200315_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.ArticleColumn', verbose_name='博客归宿栏目'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='博客阅读数量'),
        ),
    ]
