# Generated by Django 2.2 on 2020-03-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='article/%Y-%m-%d', verbose_name='博客封面'),
        ),
    ]
