# Generated by Django 2.2 on 2020-03-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '02-用户信息详细表', 'verbose_name_plural': '02-用户信息详细表'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='02-用户信息详细表',
        ),
    ]
